substitutions:
  device_name: appendix_sht20
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

esphome:
  libraries:
    - "Wire"
    - "ArduinoJson"
    - "uFire SHT20"
  includes:
    - include/sht20.h

i2c:
  frequency: 200kHz

sensor:
  - platform: custom
    lambda: |-
      auto sht20 = new SHT20();
      App.register_component(sht20);
      return {sht20->temperature_sensor, sht20->humidity_sensor};
    sensors:
      - name: "Temperature"
        unit_of_measurement: °C
        accuracy_decimals: 2
      - name: "Humidity"
        unit_of_measurement: "%"
        accuracy_decimals: 2

<<: !include common/mqtt.yaml
