substitutions:
  device_name: chapter5_soil_moisture2
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    id: led

sensor:
  - platform: adc
    pin: GPIO33
    name: "Soil Moisture"
    attenuation: 11db
    update_interval: 5min
    unit_of_measurement: "%"
    icon: "mdi:flower-outline"
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
          - 0.0 -> 0
          - 2.9 -> 100
      - lambda: return min(100.0f, x);
    on_value_range:
      - above: 40
        then:
          - switch.turn_off: led
      - below: 40
        then:
          - switch.turn_on: led

<<: !include common/mqtt.yaml
