substitutions:
  device_name: chapter3_led
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    name: "LED"

<<: !include common/mqtt.yaml
