substitutions:
  device_name: chapter4_night_light
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    id: led

time:
  - platform: sntp

sun:
  latitude: 51.8796
  longitude: 5.8527
  on_sunset:
    - then:
        - switch.turn_on: led
  on_sunrise:
    - then:
        - switch.turn_off: led

<<: !include common/mqtt.yaml
