substitutions:
  device_name: chapter3_pir
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

binary_sensor:
  - platform: gpio
    pin: GPIO21
    name: "PIR sensor"
    device_class: motion

<<: !include common/mqtt.yaml
