substitutions:
  device_name: chapter2_package2
  device_platform: ESP32
  device_board: featheresp32

esphome:
  libraries:
    - "uFire SHT20"
    - "ArduinoJson"
  includes:
    - include/sht20.h

packages:
  base: !include common/base.yaml
