substitutions:
  device_name: chapter3_ledc
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

output:
  - platform: ledc
    pin: GPIO32
    id: gpio_32

light:
  - platform: monochromatic
    output: gpio_32
    name: "Dimmable LED"

<<: !include common/mqtt.yaml
