substitutions:
  device_name: chapter5_distance
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    id: led

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO21
    echo_pin: GPIO37
    name: "Distance"
    update_interval: 1s
    on_value_range:
      - below: 0.11
        then:
          - switch.turn_on: led
      - above: 0.10
        then:
          - switch.turn_off: led

<<: !include common/mqtt.yaml
