substitutions:
  device_name: chapter4_led_toggle
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    id: led

interval:
  - interval: 1s
    then:
      - switch.toggle: led

<<: !include common/mqtt.yaml
