substitutions:
  device_name: chapter2_package
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

binary_sensor:
  - platform: gpio
    pin: GPIO35
    name: "Button 1"

<<: !include common/mqtt.yaml
