substitutions:
  device_name: chapter5_light
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    id: led

sensor:
  - platform: adc
    pin: GPIO33
    name: "Illuminance"
    attenuation: 11db
    unit_of_measurement: lx
    update_interval: 1s
    filters:
      - lambda: return (x / 10000.0) * 2000000.0;
    on_value_range:
      - above: 1
        then:
          - switch.turn_off: led
      - below: 1
        then:
          - switch.turn_on: led

<<: !include common/mqtt.yaml
