substitutions:
  device_name: chapter4_pir_led_switch
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    id: led

binary_sensor:
  - platform: gpio
    pin: GPIO21
    id: led_enabled
    name: "Enable LED"
  - platform: gpio
    pin: GPIO22
    name: "PIR sensor"
    device_class: motion
    on_press:
      then:
        - if:
            condition:
              - binary_sensor.is_on: led_enabled
            then:
              - switch.turn_on: led
              - delay: 10s
            else:
              - logger.log: "Motion detected"
        - switch.turn_off: led

<<: !include common/mqtt.yaml
