substitutions:
  device_name: chapter4_pir_led_button
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    id: led

binary_sensor:
  - platform: gpio
    pin: GPIO21
    id: reset_button
    name: "Reset button"
    on_press:
      then:
        - script.execute: turn_off_led
  - platform: gpio
    pin: GPIO22
    name: "PIR sensor"
    device_class: motion
    on_press:
      then:
        - script.execute: turn_on_led

script:
  - id: turn_on_led
    mode: restart
    then:
      - switch.turn_on: led
      - delay: 1min
      - switch.turn_off: led
  - id: turn_off_led
    then:
      - script.stop: turn_on_led
      - switch.turn_off: led

<<: !include common/mqtt.yaml
