substitutions:
  device_name: chapter5_soil_moisture
  device_platform: ESP32
  device_board: featheresp32

packages:
  base: !include common/base.yaml

switch:
  - platform: gpio
    pin: GPIO32
    name: "LED"

sensor:
  - platform: adc
    pin: GPIO33
    name: "Soil Moisture"
    attenuation: 11db
    update_interval: 1s

<<: !include common/mqtt.yaml
